import { Vault, ConditionMeta, ConditionType, Query } from "@/types"

export const CONDITION_TYPES: Record<ConditionType, ConditionMeta> = {
  price:     { icon: "Lock",   label: "Price gate",        desc: "Pay the listed IP token amount per query." },
  time:      { icon: "Clock",  label: "Time lock",         desc: "Results are released only after the lock window." },
  whitelist: { icon: "Shield", label: "Wallet whitelist",  desc: "Only approved addresses can unlock this vault." },
  deadman:   { icon: "Skull",  label: "Dead man's switch", desc: "Vault auto-deletes if the provider stops renewing." },
}

export const VAULTS: Vault[] = [
  {
    id: "vlt-genome-7",
    name: "Helix Cohort 7",
    category: "Medical",
    desc: "De-identified whole-genome sequencing from a 12,400-patient oncology cohort. Variant calls queryable, raw reads never leave the enclave.",
    price: 240,
    queries: 1832,
    provider: "0x7Ad4c91F2bE0a9d3F1c8B45e6712aC3D90eF4521",
    liveQueried: true,
    schema: ["patient_pseudo_id", "chromosome", "variant_call", "zygosity", "gene_symbol", "clinvar_sig", "tumor_stage", "age_band"],
    conditions: ["price", "whitelist"],
    status: "active",
    earnings: 4128,
    lastQueried: "2m ago",
  },
  {
    id: "vlt-fx-flow",
    name: "Sovereign FX Flows",
    category: "Financial",
    desc: "Anonymized institutional FX settlement flows across 9 venues. Aggregate volumes and directional bias only — no counterparty identity.",
    price: 1500,
    queries: 642,
    provider: "0x33Bc7E10aF45920DdE1b6c8049fA2517c0B8e7a4",
    liveQueried: true,
    schema: ["venue_hash", "currency_pair", "notional_band", "direction", "settle_window", "spread_bps"],
    conditions: ["price", "time"],
    status: "active",
    earnings: 18600,
    lastQueried: "14m ago",
  },
  {
    id: "vlt-arctic-co2",
    name: "Arctic Methane Grid",
    category: "Environmental",
    desc: "High-resolution permafrost methane flux readings from 340 autonomous sensors across the Siberian shelf, updated hourly.",
    price: 80,
    queries: 2910,
    provider: "0x9F2a18Dc7740bB3e6512ac09D8fE4471aB30c95d",
    liveQueried: true,
    schema: ["sensor_id", "lat_band", "lon_band", "ch4_ppm", "soil_temp_c", "reading_ts"],
    conditions: ["price"],
    status: "active",
    earnings: 2320,
    lastQueried: "just now",
  },
  {
    id: "vlt-rx-adh",
    name: "Adherence Signals",
    category: "Medical",
    desc: "Pharmacy refill and adherence telemetry across four chronic-disease classes. Aggregated to ZIP-3 to preserve privacy.",
    price: 460,
    queries: 388,
    provider: "0x12Ee904A2b71cDF03856ac1209FE4471Bb30c2a1",
    liveQueried: false,
    schema: ["zip3", "drug_class", "refill_gap_days", "adherence_band", "age_band", "season"],
    conditions: ["price", "whitelist", "deadman"],
    status: "active",
    earnings: 1786,
    lastQueried: "3d ago",
  },
  {
    id: "vlt-credit-thin",
    name: "Thin-File Credit Graph",
    category: "Financial",
    desc: "Alternative-data credit signals for thin-file borrowers — rent, utility, and telecom payment regularity, fully tokenized.",
    price: 920,
    queries: 1204,
    provider: "0x55Ca72B0e9f418Dd2a6c80f49Fa2517c0Bee31b9",
    liveQueried: true,
    schema: ["borrower_hash", "rent_regularity", "util_ontime_pct", "telecom_tenure_m", "thin_file_flag"],
    conditions: ["price", "time", "whitelist"],
    status: "active",
    earnings: 11040,
    lastQueried: "41m ago",
  },
  {
    id: "vlt-reef-bleach",
    name: "Coral Bleaching Index",
    category: "Environmental",
    desc: "Satellite-derived sea-surface temperature anomalies and bleaching probability scores for 1,800 monitored reef segments.",
    price: 60,
    queries: 4421,
    provider: "0x88Fd33aC1b07e29Dd45c6f8049Fa2517c0Be90c2",
    liveQueried: true,
    schema: ["reef_segment", "sst_anomaly_c", "bleach_prob", "depth_band", "obs_date"],
    conditions: ["price"],
    status: "active",
    earnings: 2640,
    lastQueried: "6m ago",
  },
  {
    id: "vlt-clinical-nlp",
    name: "Clinical Note Embeddings",
    category: "Medical",
    desc: "Vector embeddings of 2.1M de-identified clinical notes. Similarity search exposed; source text remains sealed in the enclave.",
    price: 380,
    queries: 70,
    provider: "0x41Bb09Dc7740aA3e6512ac09D8fE4471aB30c12f",
    liveQueried: false,
    schema: ["note_vector_id", "specialty", "embed_dim_0_511", "encounter_type", "year_band"],
    conditions: ["price", "whitelist"],
    status: "paused",
    earnings: 540,
    lastQueried: "9d ago",
  },
  {
    id: "vlt-grid-load",
    name: "Grid Load Microforecasts",
    category: "Other",
    desc: "Minute-level distribution-grid load forecasts for 60 substations. Residuals and confidence bands queryable in aggregate.",
    price: 210,
    queries: 988,
    provider: "0x7700aaB0e9f418Dd2a6c80f49Fa2517c0Bee44d3",
    liveQueried: true,
    schema: ["substation_hash", "load_kw_band", "forecast_residual", "confidence", "interval_ts"],
    conditions: ["price", "deadman"],
    status: "expired",
    earnings: 3150,
    lastQueried: "22d ago",
  },
]

export const CATEGORIES = ["All", "Medical", "Financial", "Environmental", "Other"]
export const SORTS = ["Newest", "Price", "Most Queried"]

export function queryHistoryFor(id: string): Query[] {
  const seed = id.length
  const base: Query[] = [
    { q: "SELECT gene_symbol, COUNT(*) FROM cohort WHERE clinvar_sig = 'pathogenic' GROUP BY gene_symbol", hash: "0x4f9a…c012", when: "2m ago" },
    { q: "SELECT AVG(adherence_band) FROM vault WHERE drug_class = 'statin'", hash: "0xab31…7f4e", when: "18m ago" },
    { q: "SELECT direction, COUNT(*) FROM flows WHERE currency_pair = 'EURUSD'", hash: "0x90c2…1ab9", when: "1h ago" },
    { q: "SELECT MAX(ch4_ppm), lat_band FROM grid GROUP BY lat_band ORDER BY 1 DESC LIMIT 10", hash: "0x12fe…44d3", when: "3h ago" },
    { q: "SELECT bleach_prob FROM reefs WHERE sst_anomaly_c > 2.0", hash: "0x55ca…31b9", when: "5h ago" },
    { q: "SELECT confidence FROM forecast WHERE forecast_residual > 0.15", hash: "0x7700…e90c", when: "yesterday" },
  ]
  return base.slice(0, 4 + (seed % 3))
}

export const MY_VAULTS = ["vlt-genome-7", "vlt-fx-flow", "vlt-rx-adh", "vlt-clinical-nlp", "vlt-grid-load"]
  .map(id => VAULTS.find(v => v.id === id)!)
